apiVersion: v1
kind: ConfigMap
metadata:
  name: pccs-config
  namespace: {{ .Values.namespace }}
data:
  default.json: |
    {
        "HTTPS_PORT": {{ .Values.pccs.httpsPort }},
        "hosts": "0.0.0.0",
        "uri": "https://api.trustedservices.intel.com/sgx/certification/v4/",
        "ApiKey": "",
        "proxy": "",
        "RefreshSchedule": "0 0 1 * *",
        "UserTokenHash": {{ .Values.pccs.userTokenHash | quote }},
        "AdminTokenHash": {{ .Values.pccs.adminTokenHash | quote }},
        "CachingFillMode": {{ .Values.pccs.cachingFillMode | quote }},
        "LogLevel": {{ .Values.pccs.logLevel | quote }},
        "DB_CONFIG": "sqlite",
        "sqlite": {
            "database": "data/pckcache.db",
            "options": {
                "dialect": "sqlite",
                "storage": "data/pckcache.db",
                "logging": false
            }
        }
    }
