apiVersion: v1
kind: Service
metadata:
  name: pccs
  namespace: {{ .Values.namespace }}
  labels:
    app: pccs
spec:
  {{- if .Values.nodePort }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.pccs.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: pccs
