{{- if not .Values.tls.generate }}
{{- if not .Values.tls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: pccs-tls
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install
type: kubernetes.io/tls
stringData:
  tls.key: "REPLACE_ME"
  tls.crt: "REPLACE_ME"
{{- end }}
{{- end }}
